/* Research-source article renderer. Uses data/daily-articles.json generated by scripts/build_article_feed.py. */
(() => {
  'use strict';
  const dataUrl = 'data/daily-articles.json';
  const formatDate = (value) => {
    try { return new Intl.DateTimeFormat('en', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)); }
    catch { return ''; }
  };
  const updateCard = (card, article) => {
    const title = card.querySelector('h1,h2,h3,h4');
    const titleLink = title && title.closest('a');
    const image = card.querySelector('img');
    const links = card.querySelectorAll('a');
    if (title) title.textContent = article.title;
    links.forEach((link) => {
      link.href = article.url;
      link.target = '_blank';
      link.rel = 'noopener noreferrer';
    });
    if (titleLink) titleLink.title = article.title;
    if (image && article.image) { image.src = article.image; image.alt = article.title; }
    const content = card.querySelector('.content, .title-row') || title?.parentElement;
    if (!content) return;
    let deck = content.querySelector('.bareboard-source-dek');
    if (!deck) {
      deck = document.createElement('p');
      deck.className = 'bareboard-source-dek';
      content.appendChild(deck);
    }
    deck.textContent = article.summary;
    let credit = content.querySelector('.bareboard-source-credit');
    if (!credit) {
      credit = document.createElement('div');
      credit.className = 'bareboard-source-credit';
      content.appendChild(credit);
    }
    credit.textContent = `Source: ${article.source}${article.published ? ' · ' + formatDate(article.published) : ''}`;
    card.dataset.bareboardSource = article.source;
  };
  fetch(dataUrl, { cache: 'no-store' })
    .then((response) => response.ok ? response.json() : Promise.reject(new Error('Daily source feed unavailable')))
    .then((payload) => {
      const articles = Array.isArray(payload.articles) ? payload.articles : [];
      if (!articles.length) return;
      const cards = Array.from(document.querySelectorAll('main .story-item'));
      // Do not cycle source stories: a source item can appear only once in the listing.
      cards.slice(0, articles.length).forEach((card, index) => updateCard(card, articles[index]));
    })
    .catch(() => { /* Existing [DEMO] content remains visible if the daily feed is unavailable. */ });
})();
