/* Research-source article renderer. Uses data/daily-articles.json generated by scripts/build_article_feed.py. */
(() => {
  'use strict';
  const dataUrl = () => `data/daily-articles.json?v=${Date.now()}`;
  const formatDate = (value) => {
    try { return new Intl.DateTimeFormat('en', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)); }
    catch { return ''; }
  };
  const removeStockImage = (card) => {
    const image = card.querySelector('img');
    if (!image) return;
    // Never retain a clone/stock image for a source story that lacks publisher artwork.
    const media = image.closest('figure') || image;
    media.remove();
  };
  const updateCard = (card, article) => {
    const title = card.querySelector('h1,h2,h3,h4');
    const titleLink = title && title.closest('a');
    const image = card.querySelector('img');
    const links = card.querySelectorAll('a');
    if (title) title.textContent = article.title;
    links.forEach((link) => {
      link.href = article.url;
      link.target = '_blank';
      link.rel = 'noopener noreferrer';
    });
    if (titleLink) titleLink.title = article.title;
    if (image && article.image) {
      card.dataset.umsHasSourceImage = 'true';
      image.style.removeProperty('display');
      image.src = article.image;
      image.alt = article.title;
      // A broken publisher image is removed; it may never fall back to a clone image.
      image.onerror = () => { delete card.dataset.umsHasSourceImage; removeStockImage(card); };
    } else {
      delete card.dataset.umsHasSourceImage;
      removeStockImage(card);
    }
    // The complete visible card opens the authentic source. This bypasses clone-page click handlers.
    card.style.cursor = 'pointer';
    card.addEventListener('click', (event) => {
      if (event.target.closest('a, button, input')) return;
      window.open(article.url, '_blank', 'noopener,noreferrer');
    }, { capture: true });
    const content = card.querySelector('.content, .title-row') || title?.parentElement;
    if (!content) return;
    let deck = content.querySelector('.bareboard-source-dek');
    if (!deck) {
      deck = document.createElement('p');
      deck.className = 'bareboard-source-dek';
      content.appendChild(deck);
    }
    deck.textContent = article.summary;
    let credit = content.querySelector('.bareboard-source-credit');
    if (!credit) {
      credit = document.createElement('div');
      credit.className = 'bareboard-source-credit';
      content.appendChild(credit);
    }
    credit.textContent = `Source: ${article.source}${article.published ? ' · ' + formatDate(article.published) : ''}`;
    card.dataset.bareboardSource = article.source;
  };
  fetch(dataUrl(), { cache: 'no-store' })
    .then((response) => response.ok ? response.json() : Promise.reject(new Error('Daily source feed unavailable')))
    .then((payload) => {
      const articles = Array.isArray(payload.articles) ? payload.articles : [];
      const cards = Array.from(document.querySelectorAll('main .story-item'));
      if (!articles.length) {
        // A failed or empty source feed must not leave unrelated stock imagery presented as UMS reporting.
        cards.forEach(removeStockImage);
        return;
      }
      // Do not cycle source stories: a source item can appear only once in the listing.
      cards.forEach((card, index) => {
        if (index < articles.length) updateCard(card, articles[index]);
        else removeStockImage(card);
      });
    })
    .catch(() => {
      // A feed outage must not show Yahoo clone images as article images.
      document.querySelectorAll('main .story-item').forEach(removeStockImage);
    });
})();
